######################################################################
# Automatically generated by qmake (2.01a) Mon May 5 12:37:24 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cmediaplayer.h
SOURCES += cmediaplayer.cpp main.cpp
